import React, { useState, useEffect } from 'react';
import { assetService } from '../services/api';
import { ShieldAlert, Activity, CheckCircle, XCircle, AlertTriangle, Play } from 'lucide-react';

const Recommendations = () => {
  const [recommendations, setRecommendations] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const [updateMessage, setUpdateMessage] = useState('');

  const fetchRecommendations = async () => {
    try {
      const res = await assetService.getRecommendations();
      if (res.success) {
        setRecommendations(res.data);
      } else {
        setError('Failed to fetch recommendations');
      }
    } catch (err) {
      setError('Error connecting to API server');
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchRecommendations();
  }, []);

  const handleStatusChange = async (id, status) => {
    try {
      const res = await assetService.updateRecommendation(id, status);
      if (res.success) {
        setUpdateMessage(`Recommendation status updated to: ${status}`);
        setTimeout(() => setUpdateMessage(''), 3000);
        fetchRecommendations(); // reload
      }
    } catch (err) {
      alert('Error updating status');
    }
  };

  if (loading) {
    return (
      <div style={{ padding: '40px', textAlign: 'center', color: 'var(--text-secondary)' }}>
        <Activity className="simulating" style={{ marginRight: '10px' }} />
        <span>Loading decision recommendations...</span>
      </div>
    );
  }

  return (
    <div className="page-container">
      <div className="page-header-row">
        <div>
          <h1 className="page-title">Engineering Recommendation Center</h1>
          <p className="page-subtitle">
            Review recommendations generated by the physics-informed AI digital twin. Accept, reject, or schedule maintenance actions.
          </p>
        </div>
      </div>

      {updateMessage && (
        <div style={{
          backgroundColor: 'rgba(0, 242, 254, 0.12)',
          border: '1px solid var(--accent-cyan)',
          borderRadius: '8px',
          padding: '16px',
          marginBottom: '24px',
          color: 'var(--accent-cyan)',
          fontWeight: 600,
          display: 'flex',
          alignItems: 'center',
          gap: '10px'
        }}>
          <CheckCircle size={18} />
          <span>{updateMessage}</span>
        </div>
      )}

      {recommendations.length === 0 ? (
        <div className="content-card" style={{ padding: '40px', textAlign: 'center', color: 'var(--text-muted)' }}>
          No pending recommendations found. All vehicles operating nominally.
        </div>
      ) : (
        <div style={{ display: 'flex', flexDirection: 'column', gap: '20px' }}>
          {recommendations.map(rec => {
            let priorityColor = 'var(--accent-green)';
            let priorityBg = 'rgba(16, 185, 129, 0.1)';
            if (rec.priority === 'Immediate Action') {
              priorityColor = 'var(--accent-red)';
              priorityBg = 'rgba(239, 68, 68, 0.1)';
            } else if (rec.priority === 'Schedule Maintenance') {
              priorityColor = 'var(--accent-amber)';
              priorityBg = 'rgba(245, 158, 11, 0.1)';
            }

            return (
              <div
                key={rec._id}
                style={{
                  backgroundColor: 'var(--bg-secondary)',
                  border: '1px solid var(--border-color)',
                  borderRadius: '12px',
                  padding: '24px',
                  display: 'grid',
                  gridTemplateColumns: '2fr 1fr auto',
                  gap: '24px',
                  alignItems: 'start'
                }}
              >
                {/* Details Column */}
                <div>
                  <div style={{ display: 'flex', gap: '12px', alignItems: 'center', marginBottom: '12px' }}>
                    <span style={{
                      padding: '4px 10px',
                      borderRadius: '4px',
                      fontSize: '11px',
                      fontWeight: 'bold',
                      color: priorityColor,
                      backgroundColor: priorityBg
                    }}>
                      {rec.priority}
                    </span>
                    <span style={{ fontSize: '13px', color: 'var(--text-secondary)' }}>
                      Asset ID: <strong style={{ color: '#fff' }}>{rec.assetId}</strong> • Component: <strong>{rec.component}</strong>
                    </span>
                  </div>

                  <h3 style={{ fontSize: '18px', fontWeight: 700, color: '#fff', margin: '0 0 8px 0' }}>
                    {rec.problem}
                  </h3>
                  <p style={{ fontSize: '13px', color: 'var(--text-secondary)', margin: '0 0 12px 0', lineHeight: '1.5' }}>
                    <strong>Evidence:</strong> {rec.evidence}
                  </p>
                  <p style={{ fontSize: '13px', color: 'var(--text-secondary)', margin: 0, lineHeight: '1.5' }}>
                    <strong>Consequence if deferred:</strong> {rec.predictedConsequence}
                  </p>
                </div>

                {/* Financial/Savings Column */}
                <div style={{
                  backgroundColor: 'var(--bg-tertiary)',
                  border: '1px solid var(--border-color)',
                  borderRadius: '8px',
                  padding: '16px',
                  display: 'flex',
                  flexDirection: 'column',
                  gap: '12px'
                }}>
                  <div>
                    <span style={{ fontSize: '10px', color: 'var(--text-muted)', display: 'block', textTransform: 'uppercase' }}>Cost of Inaction</span>
                    <strong style={{ fontSize: '16px', color: 'var(--accent-red)' }}>₹{rec.costOfInaction.toLocaleString()}</strong>
                  </div>
                  <div>
                    <span style={{ fontSize: '10px', color: 'var(--text-muted)', display: 'block', textTransform: 'uppercase' }}>Cost of Action</span>
                    <strong style={{ fontSize: '16px', color: 'var(--accent-green)' }}>₹{rec.costOfAction.toLocaleString()}</strong>
                  </div>
                  <div style={{ borderTop: '1px solid var(--border-color)', paddingTop: '8px', display: 'flex', justifyContent: 'space-between', fontSize: '12px' }}>
                    <span style={{ color: 'var(--text-secondary)' }}>RUL Savings:</span>
                    <strong style={{ color: 'var(--accent-cyan)' }}>₹{(rec.costOfInaction - rec.costOfAction).toLocaleString()}</strong>
                  </div>
                </div>

                {/* Status and Action Buttons */}
                <div style={{ display: 'flex', flexDirection: 'column', gap: '8px', alignItems: 'flex-end', height: '100%', justifyContent: 'space-between' }}>
                  <div style={{ textAlign: 'right' }}>
                    <span style={{ fontSize: '10px', color: 'var(--text-secondary)', display: 'block' }}>Priority Score</span>
                    <strong style={{ fontSize: '20px', color: priorityColor }}>{rec.priorityScore}</strong>
                  </div>

                  <div style={{ display: 'flex', gap: '8px', marginTop: '16px' }}>
                    {rec.status === 'Pending' ? (
                      <>
                        <button
                          onClick={() => handleStatusChange(rec._id, 'Accepted')}
                          className="btn btn-primary"
                          style={{ padding: '8px 12px', fontSize: '12px' }}
                        >
                          <CheckCircle size={14} />
                          <span>Approve Action</span>
                        </button>
                        <button
                          onClick={() => handleStatusChange(rec._id, 'Rejected')}
                          className="btn"
                          style={{ padding: '8px 12px', fontSize: '12px', borderColor: 'var(--accent-red)' }}
                        >
                          <XCircle size={14} style={{ color: 'var(--accent-red)' }} />
                          <span style={{ color: 'var(--accent-red)' }}>Reject</span>
                        </button>
                      </>
                    ) : (
                      <div style={{ display: 'flex', alignItems: 'center', gap: '6px', fontSize: '13px' }}>
                        <CheckCircle size={16} style={{ color: 'var(--accent-green)' }} />
                        <span style={{ color: 'var(--accent-green)', fontWeight: 600 }}>{rec.status}</span>
                      </div>
                    )}
                  </div>
                </div>

              </div>
            );
          })}
        </div>
      )}
    </div>
  );
};

export default Recommendations;
